### ISSUE TITLE
Inaccurate usage time

### ISSUE THREAD

**Issue by OOLEHLEH** [PranavPurwar/Reef#27]
GrapheneOS Version 2025102801
Reef version 2.0.4

I've been using reef specifically for tiktok and the usage times sometimes work or don't work at all.

I have a seperate screen time app showing me my usage accurately and was wondering if theres a way to fix the issue on reef.

**Comment by PranavPurwar** [comment]
@alv-cor @OOLEHLEH @besenstue Please try v2.0.5. The issue should be fixed there.

**Comment by ImranR98** [comment]
This is still an issue on the latest v3.0.0.

I'm seeing ~35h total for last Tuesday, which is impossible. This is the same amount of time it reports for the past 7 days.

And I'm seeing ~3h40m for today, which is also impossible since it's only 12:50AM. Is it possible that some of this is related to timezones? (my current timezone is UTC+3 which kinda lines up with the extra 3 hours listed for today).

Also on GrapheneOS.

**Comment by PranavPurwar** [comment]
> This is still an issue on the latest v3.0.0 (for both individual apps and total screen time).
> 
> I'm seeing ~35h total for last Tuesday, which is impossible. This is the same amount of time it reports for the past 7 days.
> 
> And I'm seeing ~3h40m for today, which is also impossible since it's only 12:50AM. Is it possible that some of this is related to timezones? (my current timezone is UTC+3 which kinda lines up with the extra 3 hours listed for today).
> 
> Also on GrapheneOS.

Could you check v3.0.1?

**Comment by ImranR98** [comment]
On 3.0.2 the stats for the past 7 days at least seem more realistic. Will report back if anything still looks weird. Thanks!

**Comment by augustinenewman04-web** [comment]
I would like to report a possible bug regarding app usage time tracking.
I have noticed that the usage time shown in your app is consistently different from the usage time reported by Google Digital Wellbeing for the same period. Both are supposed to track screen or app usage, yet the figures do not match. Will there be an update for this?

**Comment by coder0107git** [comment]
I have also noticed this time difference. I was noticing that Google's Digital Well-being, Reef, and [Screen Time](https://f-droid.org/packages/com.soberdigital.screentimetracker) all have differing total usage time, sometimes with one higher than another and then being lower than the other the next day. 

Thanks for your work on this! I hope the latest changes fix the problem now :)
